const data = [
  {
    id: 0,
    img: '../img/product/product-1.jpg',
    img_hover: '../img/product/product-1.jpg',
    name: 'Android Mobile Dual SIM G3',
    price: 185,
    old_price: 225,
    category: 'Phones',
    brand: 'Samsung',
    color: 'black',
  },
  {
    id: 1,
    img: '../img/product/product2.jpg',
    img_hover: '../img/product/product-2.jpg',
    name: 'Android Phone Dual SIM G3',
    price: 100,
    old_price: 120,
    category: 'Phones',
    brand: 'Apple',
    color: 'blue',
  },
  {
    id: 2,
    img: '../img/product/product3.jpg',
    img_hover: '../img/product/product-3.jpg',
    name: 'LED Smart TV For 4K Gen3',
    price: 140,
    old_price: 200,
    category: 'TV',
    brand: 'Sony',
    color: 'red',
  },
  {
    id: 3,
    img: '../img/product/product4.jpg',
    img_hover: '../img/product/product-4.jpg',
    name: 'Wireless Via A Bluetooth Head',
    price: 90,
    old_price: 110,
    category: 'Electronics',
    brand: 'Sony',
    color: 'black',
  },
  {
    id: 4,
    img: '../img/product/product5.jpg',
    img_hover: '../img/product/product-5.jpg',
    name: 'Bluetooth Stereo Earbuds',
    price: 350,
    old_price: 420,
    category: 'Electronics',
    brand: 'Samsung',
    color: 'white',
  },
  {
    id: 5,
    img: '../img/product/product6.jpg',
    img_hover: '../img/product/product-6.jpg',
    name: 'Android Mobile Dual SIM G4',
    price: 115,
    old_price: 235,
    category: 'Phones',
    brand: 'Oppo',
    color: 'green',
  },
  {
    id: 6,
    img: '../img/product/product7.jpg',
    img_hover: '../img/product/product-7.jpg',
    name: 'Smart Mobile Soft Android G7',
    price: 225,
    old_price: 280,
    category: 'Phones',
    brand: 'Xiaomi',
    color: 'black',
  },
  {
    id: 7,
    img: '../img/product/product8.jpg',
    img_hover: '../img/product/product-8.jpg',
    name: 'Steel Digital Smart Watch S5',
    price: 150,
    old_price: 200,
    category: 'Watches',
    brand: 'Samsung',
    color: 'silver',
  },
  {
    id: 8,
    img: '../img/product/product-1.jpg',
    img_hover: '../img/product/product1.jpg',
    name: 'Android Smart Dual Mobile G3',
    price: 180,
    category: 'Phones',
    brand: 'Huawei',
    color: 'blue',
  },
  {
    id: 9,
    img: '../img/product/product-2.jpg',
    img_hover: '../img/product/product2.jpg',
    name: 'Android Smart Dual Phone G3',
    price: 300,
    category: 'Phones',
    brand: 'Samsung',
    color: 'black',
  },
  {
    id: 10,
    img: '../img/product/product-3.jpg',
    img_hover: '../img/product/product3.jpg',
    name: 'Smart LED TV With The 4K G3',
    price: 250,
    category: 'TV',
    brand: 'LG',
    color: 'black',
  },
  {
    id: 11,
    img: '../img/product/product-4.jpg',
    img_hover: '../img/product/product4.jpg',
    name: 'Bluetooth Smart Headset G3',
    price: 120,
    category: 'Electronics',
    brand: 'Sony',
    color: 'black',
  },
  {
    id: 12,
    img: '../img/product/product-5.jpg',
    img_hover: '../img/product/product5.jpg',
    name: 'Stereo Smart Earbuds The G3',
    price: 90,
    category: 'Electronics',
    brand: 'Apple',
    color: 'white',
  },
  {
    id: 13,
    img: '../img/product/product-6.jpg',
    img_hover: '../img/product/product6.jpg',
    name: 'Android Smart Mobile Dual G4',
    price: 129,
    category: 'Phones',
    brand: 'Oppo',
    color: 'green',
  },
  {
    id: 14,
    img: '../img/product/product-7.jpg',
    img_hover: '../img/product/product7.jpg',
    name: 'Android Smart Mobile Dual G7',
    price: 180,
    category: 'Phones',
    brand: 'Xiaomi',
    color: 'black',
  },
  {
    id: 15,
    img: '../img/product/product-8.jpg',
    img_hover: '../img/product/product8.jpg',
    name: 'Digital Steel Smart Watch S5',
    price: 60,
    category: 'Watches',
    brand: 'Samsung',
    color: 'silver',
  },
];
